version: '3'

services:
  app:
    env_file:
      - .env
    container_name: crossy-api
    restart: always
    build: .
    ports: 
      - 4000:4000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: